### PR TITLE
Support disabling prefix output

### PR DESCRIPTION
**Pull request by marcbachmann**
Add `NO_LOG_PREFIX` environment variable to disable timestamp & process name output.

```
$ NO_LOG_PREFIX=true ./exitd ./test.sh ./test.sh
Foo
Foo
test
2017/11/22 22:40:39 Command "test.sh" exited.
2017/11/22 22:40:39 Waiting for remaining processes to exit...
2017/11/22 22:40:39 Done. One or more processes exited prematurely.
```

```
$ NO_LOG_PREFIX=first ./exitd ./test.sh ./test.sh
Foo
2017/11/22 22:40:23 test.sh: Foo
test
2017/11/22 22:40:25 test.sh: test
2017/11/22 22:40:25 Command "test.sh" exited.
2017/11/22 22:40:25 Waiting for remaining processes to exit...
2017/11/22 22:40:25 Done. One or more processes exited prematurely.
```

### CODE REVIEW

**Comment by romabysen** [comment]
Nice. What do you think of prefixing the environment variable with `EXITD_` to prevent it from clashing with variables used by the child processes?

**Comment by marcbachmann** [comment]
Yep, I’m fine with that.
... i forgot that all environment variables are passed down to processes.

**Comment by marcbachmann** [comment]
I just updated the commit

**Comment by romabysen** [comment]
Nice. Sorry, got real busy at work but I'll merge this asap.

**Comment by marcbachmann** [comment]
no hurry. Thanks

**Pull request merged**
